### ISSUE TITLE
add option to just create a text file of downloadable link for internet download manager

### ISSUE THREAD

**Issue by masoudazad** [ali-0315/aparat_playlist_downloader#1]
can you add option to just export a text file of downloadable link for internet download manager?
thanks

**Comment by ali-0315** [comment]
> can you add option to just export a text file of downloadable link for internet download manager?
> thanks

Yeah, it's possible

**Comment by AliAkbarSobhanpour** [comment]
> can you add option to just export a text file of downloadable link for internet download manager? thanks
i added feature to the project .
