### ISSUE TITLE
درخواست راهنمایی

### ISSUE THREAD

**Issue by Mahantor** [ali-0315/aparat_playlist_downloader#3]
من میخوام از طریق سی ام دی ویندوز فایل پایتون اجرا کنم ولی ارور میده امکانش هست راهنماییم کنید

C:\yt-dlp\aparat_playlist_downloader>python3 main.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\yt-dlp\aparat_playlist_downloader>python --version
Python 3.12.4

C:\yt-dlp\aparat_playlist_downloader>pip --version
pip 24.0 from C:\Program Files\Python312\Lib\site-packages\pip (python 3.12)

**Comment by ali-0315** [comment]
سلام 
توی ویندوز احتمالا باید بزنید 
python main.py

python3 برای لینوکس هستش

**Comment by Mahantor** [comment]
ممنون

**Comment by Mahantor** [comment]
الان این ارور میده
We have some errors in getting API data!
..........................................
PS C:\Users\USER\Desktop\aparat_playlist_downloader-main> python main.py
Give me a Aparat playlist id: https://www.aparat.com/v/z694m52
Give me the quality: (Examples: 144 , 240 , 360 , 480 , 720 , 1080) :480
Type "y" if you want to create a .txt file that contain all the videos link otherwise type "n" to start download now:y
We have some errors in getting API data!

**Comment by ali-0315** [comment]
> ممنون



> الان این ارور میده We have some errors in getting API data! .......................................... PS C:\Users\USER\Desktop\aparat_playlist_downloader-main> python main.py Give me a Aparat playlist id: https://www.aparat.com/v/z694m52 Give me the quality: (Examples: 144 , 240 , 360 , 480 , 720 , 1080) :480 Type "y" if you want to create a .txt file that contain all the videos link otherwise type "n" to start download now:y We have some errors in getting API data!

این اسکریپت میره پلی لیست دانلود میکنه نه خود ویدئو رو
و شما فقط کافیه آیدی پلی لیست رو بدید بهش
مثلا برای دانلود این پلی لیست : https://www.aparat.com/playlist/418751 
باید بهش 418751 رو بدید

البته امکان اضافه شدن این مورد هم هست که ویدئو تکی دانلود کنه ، یه issue باز کنید تا اضافه ش کنم این قابلیت رو
