### ISSUE TITLE
مشکل با تعداد لینک استخراج شده

### ISSUE THREAD

**Issue by Mahantor** [ali-0315/aparat_playlist_downloader#4]
ممنون بالاخره اسکریپت واسم کار داد ولی یه مشکلی باهاش دارم
این لینک 63 تا ویدئو داره ولی اسکریپت 62 تا لینک استخراج میکنه
https://www.aparat.com/v/z694m52?playlist=1224692
و تو این لینک 47 تا ویدئو داره ولی  50 تا لینک استخراج میشه
https://www.aparat.com/v/e69h723?playlist=1241815

چند باری امتحان کردم ولی نتیجه یکی بود
صفحه ای که ازش پلی لیست هارو گرفتم اینه
https://www.aparat.com/MohsenKalatehAhani/playlists

**Comment by ali-0315** [comment]
> ممنون بالاخره اسکریپت واسم کار داد ولی یه مشکلی باهاش دارم
> این لینک 63 تا ویدئو داره ولی اسکریپت 62 تا لینک استخراج میکنه
> https://www.aparat.com/v/z694m52?playlist=1224692
> و تو این لینک 47 تا ویدئو داره ولی  50 تا لینک استخراج میشه
> https://www.aparat.com/v/e69h723?playlist=1241815
> 
> چند باری امتحان کردم ولی نتیجه یکی بود
> صفحه ای که ازش پلی لیست هارو گرفتم اینه
> https://www.aparat.com/MohsenKalatehAhani/playlists

خواهش میکنم ، خوشحالم که واستون مفید بوده🌷

بررسی میکنم و خبرش رو بهتون میدم

**Comment by ali-0315** [comment]
> این لینک 63 تا ویدئو داره ولی اسکریپت 62 تا لینک استخراج میکنه
> https://www.aparat.com/v/z694m52?playlist=1224692

سلامی دوباره 
اینجا چک کردم مشکل این بود که ویدئو با کیفیت انتخابی پیدا نمیشد و رد میشد ، یکار کردم که از این دفعه اگه کیفیت پیدا نشد بره بهترین کیفیت رو دانلود کنه

**Comment by ali-0315** [comment]
> و تو این لینک 47 تا ویدئو داره ولی 50 تا لینک استخراج میشه https://www.aparat.com/v/e69h723?playlist=1241815

اینجا هم این پلی لیست 50 تا ویدئو داره و مشکلی نیست
![Screenshot from 2024-07-02 22-12-24](https://github.com/ali-0315/aparat_playlist_downloader/assets/80034535/8492b44f-909b-4cf8-887e-24025304a0b4)

**Comment by Mahantor** [comment]
خیلی ممنون
