### ISSUE TITLE
درخواست ویژگی جدید

### ISSUE THREAD

**Issue by Mahantor** [ali-0315/aparat_playlist_downloader#5]
سلام
امکانش هست به اسکریپت aparat_playlist_downloader  امکان گرفتن نام فایل ها رو مثل این فایل اضافه کنید
[links.txt](https://github.com/user-attachments/files/16195291/links.txt)
یک اسکریپت نوشتم به زبان پایتون که اگر فایل خروجی از پلی لیست به این فرمت باشه به طور خودکار فایل های دانلود شده به نام اصلی خودشون در پلی لیست تغییر نام داده میشن (البته این کار با زحمت و به کمک هوش مصنوعی انجام دادم ) 

[export.txt](https://github.com/user-attachments/files/16195319/export.txt)

**Comment by ali-0315** [comment]
> سلام
> امکانش هست به اسکریپت aparat_playlist_downloader  امکان گرفتن نام فایل ها رو مثل این فایل اضافه کنید
> [links.txt](https://github.com/user-attachments/files/16195291/links.txt)
> یک اسکریپت نوشتم به زبان پایتون که اگر فایل خروجی از پلی لیست به این فرمت باشه به طور خودکار فایل های دانلود شده به نام اصلی خودشون در پلی لیست تغییر نام داده میشن (البته این کار با زحمت و به کمک هوش مصنوعی انجام دادم ) 
> 
> [export.txt](https://github.com/user-attachments/files/16195319/export.txt)
> 

سلام 
متأسفانه امکان اضافه شدن این قابلیت وجود نداره ، چون هدف از این قابلیت این بود که بشه برای نرم افزار هایی مثل IDM مورد استفاده قرار بگیرن

اگه فایل ها رو با خود اسکریپت دانلود کنید ، اسم هاشون رو درست می کنه و براتون ذخیره میکنه
